apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  source:
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 4.5.5
    chart: nextcloud
    helm:
      parameters: []
      values: []