apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-server
spec:
  selector:
    matchLabels:
      app: mc-server
  template:
    metadata:
      labels:
        app: mc-server
    spec:
      containers:
      - name: mc-server
        image: itzg/minecraft-server
        env:
          - name: EULA
            value: "TRUE"
        resources:
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        ports:
        - containerPort: 25565
---
apiVersion: v1
kind: Service
metadata:
  name: mc-service
spec:
  selector:
    app: mc-server
  ports:
  - port: 25565
    targetPort: 25565
  type: LoadBalancer