apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
  namespace: nextcloud
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "100Gi"
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/home/core/nextcloud"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Gi"